tag-prefix: ''
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '🐳 Docker & Deployment'
    labels:
      - 'docker'
      - 'deployment'
      - 'infrastructure'
  - title: '🔧 Configuration'
    labels:
      - 'config'
      - 'configuration'
  - title: '🔌 API Changes'
    labels:
      - 'api'
      - 'breaking-change'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

change-title-escapes: '\<*_&"'''
autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**/*'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
    title:
      - '/fix/i'
      - '/bug/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/enhancement\/.+/'
  - label: 'docker'
    files:
      - 'Dockerfile'
      - 'compose.yaml'
      - '.dockerignore'
  - label: 'config'
    files:
      - 'config.json'
      - 'requirements.txt'
  - label: 'api'
    files:
      - 'main.py'
    branch:
      - '/api\/.+/'
  - label: 'security'
    branch:
      - '/security\/.+/'
replacers:
  - search: /"/g
    replace: ''
  - search: /'/g
    replace: ''
exclude-labels:
  - 'skip-changelog'

filter-by-commitish: true
